# Generated by Django 2.0.7 on 2018-07-20 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20180720_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='Question',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', to='poll.Questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
