# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
