# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredb', '0002_auto_20171226_1642'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='catagory',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
